#spring:
#  profiles:
#    active: kafka
#  datasource:
#    url: jdbc:mysql://localhost:3306/eventdb
#    username: max
#    password: 1111
#  jpa:
#    hibernate:
#      use-new-id-generator-mappings: false
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    properties:
#      show_sql: true